all:
  hosts:
    jenkins:
      ansible_host: "{{ lookup('env', 'JENKINS_PUBLIC_DNS') | default('replace-with-public-dns', true) }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ playbook_dir }}/jenkinscicd.pem"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  vars:
    ansible_python_interpreter: /usr/bin/python3

